/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyAccessControlInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowUser"
      | "allowUserWithEntropy"
      | "allowedUsers"
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEncryptedValue"
      | "getEntropyOracle"
      | "initialize"
      | "isUserAllowed"
      | "performTransientOperation"
      | "requestEntropy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyAccessGranted"
      | "EntropyRequested"
      | "TransientOperation"
      | "UserAllowed"
      | "UserRevoked"
      | "ValueStored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowUserWithEntropy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performTransientOperation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "allowUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowUserWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUserAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performTransientOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
}

export namespace EntropyAccessGrantedEvent {
  export type InputTuple = [requestId: BigNumberish, user: AddressLike];
  export type OutputTuple = [requestId: bigint, user: string];
  export interface OutputObject {
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransientOperationEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAllowedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRevokedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyAccessControl extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyAccessControl;
  waitForDeployment(): Promise<this>;

  interface: EntropyAccessControlInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowUser: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  allowUserWithEntropy: TypedContractMethod<
    [user: AddressLike, requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  allowedUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEncryptedValue: TypedContractMethod<[], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  isUserAllowed: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  performTransientOperation: TypedContractMethod<
    [user: AddressLike],
    [string],
    "nonpayable"
  >;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowUserWithEntropy"
  ): TypedContractMethod<
    [user: AddressLike, requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowedUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isUserAllowed"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "performTransientOperation"
  ): TypedContractMethod<[user: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getEvent(
    key: "EntropyAccessGranted"
  ): TypedContractEvent<
    EntropyAccessGrantedEvent.InputTuple,
    EntropyAccessGrantedEvent.OutputTuple,
    EntropyAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TransientOperation"
  ): TypedContractEvent<
    TransientOperationEvent.InputTuple,
    TransientOperationEvent.OutputTuple,
    TransientOperationEvent.OutputObject
  >;
  getEvent(
    key: "UserAllowed"
  ): TypedContractEvent<
    UserAllowedEvent.InputTuple,
    UserAllowedEvent.OutputTuple,
    UserAllowedEvent.OutputObject
  >;
  getEvent(
    key: "UserRevoked"
  ): TypedContractEvent<
    UserRevokedEvent.InputTuple,
    UserRevokedEvent.OutputTuple,
    UserRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ValueStored"
  ): TypedContractEvent<
    ValueStoredEvent.InputTuple,
    ValueStoredEvent.OutputTuple,
    ValueStoredEvent.OutputObject
  >;

  filters: {
    "EntropyAccessGranted(uint256,address)": TypedContractEvent<
      EntropyAccessGrantedEvent.InputTuple,
      EntropyAccessGrantedEvent.OutputTuple,
      EntropyAccessGrantedEvent.OutputObject
    >;
    EntropyAccessGranted: TypedContractEvent<
      EntropyAccessGrantedEvent.InputTuple,
      EntropyAccessGrantedEvent.OutputTuple,
      EntropyAccessGrantedEvent.OutputObject
    >;

    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "TransientOperation(address)": TypedContractEvent<
      TransientOperationEvent.InputTuple,
      TransientOperationEvent.OutputTuple,
      TransientOperationEvent.OutputObject
    >;
    TransientOperation: TypedContractEvent<
      TransientOperationEvent.InputTuple,
      TransientOperationEvent.OutputTuple,
      TransientOperationEvent.OutputObject
    >;

    "UserAllowed(address)": TypedContractEvent<
      UserAllowedEvent.InputTuple,
      UserAllowedEvent.OutputTuple,
      UserAllowedEvent.OutputObject
    >;
    UserAllowed: TypedContractEvent<
      UserAllowedEvent.InputTuple,
      UserAllowedEvent.OutputTuple,
      UserAllowedEvent.OutputObject
    >;

    "UserRevoked(address)": TypedContractEvent<
      UserRevokedEvent.InputTuple,
      UserRevokedEvent.OutputTuple,
      UserRevokedEvent.OutputObject
    >;
    UserRevoked: TypedContractEvent<
      UserRevokedEvent.InputTuple,
      UserRevokedEvent.OutputTuple,
      UserRevokedEvent.OutputObject
    >;

    "ValueStored(address)": TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
    ValueStored: TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
  };
}
